version: '3.4'

services:
  
  #Databases
  stockdb:
    container_name: stockdb
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1Secure*Password1
      - MSSQL_PID=Express
    ports:
      - "1500:1433"

  catalogdb:
    container_name: catalogdb
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1Secure*Password1
      - MSSQL_PID=Express
    ports:
      - "1501:1433"

  orderdb:
    container_name: orderdb
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1Secure*Password1
      - MSSQL_PID=Express
    ports:
      - "1502:1433"

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"


  #Services
  stock.api:
    container_name: stock.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=stockdb;Database=StockDb;uid=sa;Pwd=1Secure*Password1;Trusted_Connection=False;Encrypt=False"
    ports:
      - "8000:80"
    depends_on:
      - stockdb

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=catalogdb;Database=CatalogDb;uid=sa;Pwd=1Secure*Password1;Trusted_Connection=False;Encrypt=False"
    ports:
      - "8001:80"
    depends_on:
      - catalogdb


  basket.api:
    container_name: Basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=basketdb:6379"
    ports:
      - "8002:80"
    depends_on:
      - basketdb
