version: '3.4'

services:

  #Databases
  stockdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  catalogdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  basketdb:
    image: redis:alpine


  #Services
  stock.api:
    image: ${DOCKER_REGISTRY-}stockapi
    build:
      context: .
      dockerfile: Services/Stock.API/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket.API/Dockerfile