version: '3.4'

services:
  #Event bus
  rabbitmq:
    image: rabbitmq:3-management-alpine

  #Databases
  stockdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  catalogdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  basketdb:
    image: redis:alpine


  #Services
  stock.api:
    image: ${DOCKER_REGISTRY-}stockapi
    build:
      context: .
      dockerfile: Services/Stock.API/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket.API/Dockerfile

  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Services/Order.API/Dockerfile

  product.aggregator:
    image: ${DOCKER_REGISTRY-}productaggregator
    build:
      context: .
      dockerfile: Gateways/Product.Aggregator/Dockerfile

  ocelotgateway:
    image: ${DOCKER_REGISTRY-}ocelotgateway
    build:
      context: .
      dockerfile: Gateways/OcelotGateway/Dockerfile

  order.processor:
    image: ${DOCKER_REGISTRY-}orderprocessor
    build:
      context: .
      dockerfile: Services/Order.Processor/Dockerfile